spring:
  application:
    name: Product-Service
  config:
    import: "optional:configserver:http://localhost:8088"

management:
  tracing:
    sampling:
      probability: 1.0

#
## server port configuration
#server:
#    port: 8081
## eureka client configuration to register with eureka server
#eureka:
#    client:
#     service-url:
#      defaultZone: http://localhost:8761/eureka/
